(define (make-account balance password)
  (let ((counter 0)) 
(define (withdraw amount)
      (if (> balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds")) 
(define (deposit amount)
      (set! balance (+ balance amount))
      balance) 
(define (test-pwd pwd)
    (if (eq? pwd password)
      (begin (set! counter 0) #t)
      (begin (set! counter (+ counter 1))
             (display "counter")
             (display counter)
             (if (> counter 3) (display "calling the cop"))
             #f))) 
(define (wrong-pwd amount)
  (display "Wrong Password"))
(define (dispatch inputpassword m)
      (if (test-pwd inputpassword)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request: MAKE-ACCOUNT")))
        wrong-pwd)) dispatch))
;; test code
(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 10)
((acc 'secret-passw 'withdraw) 20)
((acc 'secret-passw 'withdraw) 20)
((acc 'secret-passw 'withdraw) 20)
((acc 'secret-passw 'withdraw) 20)
