(define (make-account balance password)
  (let ((counter 0)) 
(define (withdraw amount)
      (if (> balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds")) 
(define (deposit amount)
      (set! balance (+ balance amount))
      balance) 
(define (test-pwd pwd)
     (if   (eq? pwd password)
       (begin (set! counter 0)
              #t)
       #f
       ) )
(define (wrong-pwd amount)
       (set! counter (+ counter 1))
       (display "counter")
       (display counter)
       (if (> counter 3) (display "calling the cop")) 
  (display "Wrong Password"))
(define (dispatch inputpassword m)
      (if (test-pwd inputpassword)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request: MAKE-ACCOUNT")))
        wrong-pwd)) dispatch))
;; test code
(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 10)
((acc 'secret-passw 'withdraw) 20)
((acc 'secret-passw 'withdraw) 20)
((acc 'secret-passw 'withdraw) 20)
((acc 'secret-passw 'withdraw) 20)
(define (make-joint account oldpwd jointpwd)
  (define (joint pwd operation)
    (if (eq? pwd jointpwd)
      (account oldpwd operation)
      (account pwd operation)))
  joint)
(display newline)
(display "new")
(define peter-acc (make-account 100 'open-sesame))
(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))
((paul-acc 'rosebud 'withdraw) 30)
