(define modulus   (expt 2 32)) 
(define multiplier   1664525) 
(define increment   1013904223) 
(define  (rand-update x)
    (modulo  (+  (* multiplier  x)  increment )   modulus ))
(define  rand  
  (let ((x 137))
    (define (generate)
      (set! x (rand-update x))
      x)
    (define (reset)
      (set! x 137)
      'done)
    (define (dispatch m)
      (cond ((eq? m 'generate) (generate))
            ((eq? m 'reset) (reset))
            (else (error "Unknow operation: random"))))
    dispatch))
(rand 'generate)
(rand 'generate)
(rand 'reset)
(rand 'generate)
