(define (square x) (* x x))
(define (iterative-improve good-enough? improve)
  (define (iter guess)
    (if (good-enough? guess)
      guess
      (iter (improve guess))))
  (lambda (guess)
    (iter guess)))
(define (sqrt x)
  ((iterative-improve (lambda (guess)
                        (< (abs (- (square guess) x)) 0.001))
                      (lambda (guess)
                        (average guess (/ x guess)))) 1.0))
(define (average a b)
  (/ (+ a b) 2))
(sqrt 3)
