(define (square x) (* x x))
(define (smallest-divisor n)
  (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (next test-divisor)))))
(define (divides? divisor n)
  (= (remainder n divisor) 0))
(define (prime? n)
  (= (smallest-divisor n) n))
(define (next a)
  (if (= a 2) 3
    (+ a 2)))
